kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "nfdataexplorer.fullname" . }}
  labels:
    {{- include "nfdataexplorer.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce 
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
