apiVersion: v1
kind: Service
metadata:
  name: {{ include "nfdataexplorer.fullname" . }}
  labels:
    {{- include "nfdataexplorer.labels" . | nindent 4 }}
spec:
  type: ClusterIP 
  ports:
    - port: 80 
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nfdataexplorer.selectorLabels" . | nindent 4 }}
